/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LocationList,
} from '../models/index';
import {
    LocationListFromJSON,
    LocationListToJSON,
} from '../models/index';

export interface Verb3Request {
    originCoordLat: number;
    originCoordLong: number;
    requestId?: string;
    format?: Verb3FormatEnum;
    jsonpCallback?: string;
    lang?: string;
    type?: Verb3TypeEnum;
}

/**
 * 
 */
export class AddresslookupApi extends runtime.BaseAPI {

    /**
     * Address Lookup
     */
    async verb3Raw(requestParameters: Verb3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LocationList>> {
        if (requestParameters.originCoordLat === null || requestParameters.originCoordLat === undefined) {
            throw new runtime.RequiredError('originCoordLat','Required parameter requestParameters.originCoordLat was null or undefined when calling verb3.');
        }

        if (requestParameters.originCoordLong === null || requestParameters.originCoordLong === undefined) {
            throw new runtime.RequiredError('originCoordLong','Required parameter requestParameters.originCoordLong was null or undefined when calling verb3.');
        }

        const queryParameters: any = {};

        if (requestParameters.requestId !== undefined) {
            queryParameters['requestId'] = requestParameters.requestId;
        }

        if (requestParameters.format !== undefined) {
            queryParameters['format'] = requestParameters.format;
        }

        if (requestParameters.jsonpCallback !== undefined) {
            queryParameters['jsonpCallback'] = requestParameters.jsonpCallback;
        }

        if (requestParameters.lang !== undefined) {
            queryParameters['lang'] = requestParameters.lang;
        }

        if (requestParameters.originCoordLat !== undefined) {
            queryParameters['originCoordLat'] = requestParameters.originCoordLat;
        }

        if (requestParameters.originCoordLong !== undefined) {
            queryParameters['originCoordLong'] = requestParameters.originCoordLong;
        }

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["accessId"] = this.configuration.apiKey("accessId"); // accessId authentication
        }

        const response = await this.request({
            path: `/addresslookup`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LocationListFromJSON(jsonValue));
    }

    /**
     * Address Lookup
     */
    async verb3(requestParameters: Verb3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LocationList> {
        const response = await this.verb3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const Verb3FormatEnum = {
    Xml: 'xml',
    Json: 'json',
    Jsonp: 'jsonp'
} as const;
export type Verb3FormatEnum = typeof Verb3FormatEnum[keyof typeof Verb3FormatEnum];
/**
 * @export
 */
export const Verb3TypeEnum = {
    A: 'A',
    All: 'ALL',
    Ap: 'AP',
    C: 'C',
    P: 'P',
    S: 'S',
    Sa: 'SA',
    Sap: 'SAP',
    Sp: 'SP'
} as const;
export type Verb3TypeEnum = typeof Verb3TypeEnum[keyof typeof Verb3TypeEnum];
