/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DataInfo,
} from '../models/index';
import {
    DataInfoFromJSON,
    DataInfoToJSON,
} from '../models/index';

export interface Verb13Request {
    requestId?: string;
    format?: Verb13FormatEnum;
    jsonpCallback?: string;
}

/**
 * 
 */
export class DatainfoApi extends runtime.BaseAPI {

    /**
     * Data Info
     */
    async verb13Raw(requestParameters: Verb13Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataInfo>> {
        const queryParameters: any = {};

        if (requestParameters.requestId !== undefined) {
            queryParameters['requestId'] = requestParameters.requestId;
        }

        if (requestParameters.format !== undefined) {
            queryParameters['format'] = requestParameters.format;
        }

        if (requestParameters.jsonpCallback !== undefined) {
            queryParameters['jsonpCallback'] = requestParameters.jsonpCallback;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["accessId"] = this.configuration.apiKey("accessId"); // accessId authentication
        }

        const response = await this.request({
            path: `/datainfo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataInfoFromJSON(jsonValue));
    }

    /**
     * Data Info
     */
    async verb13(requestParameters: Verb13Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataInfo> {
        const response = await this.verb13Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const Verb13FormatEnum = {
    Xml: 'xml',
    Json: 'json',
    Jsonp: 'jsonp'
} as const;
export type Verb13FormatEnum = typeof Verb13FormatEnum[keyof typeof Verb13FormatEnum];
