/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TripList,
} from '../models/index';
import {
    TripListFromJSON,
    TripListToJSON,
} from '../models/index';

export interface Verb10Request {
    ctx: string;
    requestId?: string;
    format?: Verb10FormatEnum;
    jsonpCallback?: string;
    lang?: string;
    poly?: Verb10PolyEnum;
    polyEnc?: Verb10PolyEncEnum;
    date?: string;
    useCombinedComparison?: Verb10UseCombinedComparisonEnum;
    acceptGaps?: Verb10AcceptGapsEnum;
    allowDummySections?: Verb10AllowDummySectionsEnum;
    flagAllNonReachable?: Verb10FlagAllNonReachableEnum;
    matchCatStrict?: Verb10MatchCatStrictEnum;
    matchIdNonBlank?: Verb10MatchIdNonBlankEnum;
    matchIdStrict?: Verb10MatchIdStrictEnum;
    matchNumStrict?: Verb10MatchNumStrictEnum;
    matchRtType?: Verb10MatchRtTypeEnum;
    enableRtFullSearch?: Verb10EnableRtFullSearchEnum;
    enableReplacements?: Verb10EnableReplacementsEnum;
    arrL?: number;
    arrU?: number;
    depL?: number;
    depU?: number;
    passlist?: Verb10PasslistEnum;
    showPassingPoints?: Verb10ShowPassingPointsEnum;
    rtMode?: Verb10RtModeEnum;
    eco?: Verb10EcoEnum;
    ecoCmp?: Verb10EcoCmpEnum;
    ecoParams?: string;
    tariff?: Verb10TariffEnum;
    trafficMessages?: Verb10TrafficMessagesEnum;
    travellerProfileData?: string;
    withJourneyBoundaryPoints?: Verb10WithJourneyBoundaryPointsEnum;
    freq?: number;
}

/**
 * 
 */
export class ReconApi extends runtime.BaseAPI {

    /**
     * Reconstruction
     */
    async verb10Raw(requestParameters: Verb10Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TripList>> {
        if (requestParameters.ctx === null || requestParameters.ctx === undefined) {
            throw new runtime.RequiredError('ctx','Required parameter requestParameters.ctx was null or undefined when calling verb10.');
        }

        const queryParameters: any = {};

        if (requestParameters.requestId !== undefined) {
            queryParameters['requestId'] = requestParameters.requestId;
        }

        if (requestParameters.format !== undefined) {
            queryParameters['format'] = requestParameters.format;
        }

        if (requestParameters.jsonpCallback !== undefined) {
            queryParameters['jsonpCallback'] = requestParameters.jsonpCallback;
        }

        if (requestParameters.lang !== undefined) {
            queryParameters['lang'] = requestParameters.lang;
        }

        if (requestParameters.ctx !== undefined) {
            queryParameters['ctx'] = requestParameters.ctx;
        }

        if (requestParameters.poly !== undefined) {
            queryParameters['poly'] = requestParameters.poly;
        }

        if (requestParameters.polyEnc !== undefined) {
            queryParameters['polyEnc'] = requestParameters.polyEnc;
        }

        if (requestParameters.date !== undefined) {
            queryParameters['date'] = requestParameters.date;
        }

        if (requestParameters.useCombinedComparison !== undefined) {
            queryParameters['useCombinedComparison'] = requestParameters.useCombinedComparison;
        }

        if (requestParameters.acceptGaps !== undefined) {
            queryParameters['acceptGaps'] = requestParameters.acceptGaps;
        }

        if (requestParameters.allowDummySections !== undefined) {
            queryParameters['allowDummySections'] = requestParameters.allowDummySections;
        }

        if (requestParameters.flagAllNonReachable !== undefined) {
            queryParameters['flagAllNonReachable'] = requestParameters.flagAllNonReachable;
        }

        if (requestParameters.matchCatStrict !== undefined) {
            queryParameters['matchCatStrict'] = requestParameters.matchCatStrict;
        }

        if (requestParameters.matchIdNonBlank !== undefined) {
            queryParameters['matchIdNonBlank'] = requestParameters.matchIdNonBlank;
        }

        if (requestParameters.matchIdStrict !== undefined) {
            queryParameters['matchIdStrict'] = requestParameters.matchIdStrict;
        }

        if (requestParameters.matchNumStrict !== undefined) {
            queryParameters['matchNumStrict'] = requestParameters.matchNumStrict;
        }

        if (requestParameters.matchRtType !== undefined) {
            queryParameters['matchRtType'] = requestParameters.matchRtType;
        }

        if (requestParameters.enableRtFullSearch !== undefined) {
            queryParameters['enableRtFullSearch'] = requestParameters.enableRtFullSearch;
        }

        if (requestParameters.enableReplacements !== undefined) {
            queryParameters['enableReplacements'] = requestParameters.enableReplacements;
        }

        if (requestParameters.arrL !== undefined) {
            queryParameters['arrL'] = requestParameters.arrL;
        }

        if (requestParameters.arrU !== undefined) {
            queryParameters['arrU'] = requestParameters.arrU;
        }

        if (requestParameters.depL !== undefined) {
            queryParameters['depL'] = requestParameters.depL;
        }

        if (requestParameters.depU !== undefined) {
            queryParameters['depU'] = requestParameters.depU;
        }

        if (requestParameters.passlist !== undefined) {
            queryParameters['passlist'] = requestParameters.passlist;
        }

        if (requestParameters.showPassingPoints !== undefined) {
            queryParameters['showPassingPoints'] = requestParameters.showPassingPoints;
        }

        if (requestParameters.rtMode !== undefined) {
            queryParameters['rtMode'] = requestParameters.rtMode;
        }

        if (requestParameters.eco !== undefined) {
            queryParameters['eco'] = requestParameters.eco;
        }

        if (requestParameters.ecoCmp !== undefined) {
            queryParameters['ecoCmp'] = requestParameters.ecoCmp;
        }

        if (requestParameters.ecoParams !== undefined) {
            queryParameters['ecoParams'] = requestParameters.ecoParams;
        }

        if (requestParameters.tariff !== undefined) {
            queryParameters['tariff'] = requestParameters.tariff;
        }

        if (requestParameters.trafficMessages !== undefined) {
            queryParameters['trafficMessages'] = requestParameters.trafficMessages;
        }

        if (requestParameters.travellerProfileData !== undefined) {
            queryParameters['travellerProfileData'] = requestParameters.travellerProfileData;
        }

        if (requestParameters.withJourneyBoundaryPoints !== undefined) {
            queryParameters['withJourneyBoundaryPoints'] = requestParameters.withJourneyBoundaryPoints;
        }

        if (requestParameters.freq !== undefined) {
            queryParameters['freq'] = requestParameters.freq;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["accessId"] = this.configuration.apiKey("accessId"); // accessId authentication
        }

        const response = await this.request({
            path: `/recon`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TripListFromJSON(jsonValue));
    }

    /**
     * Reconstruction
     */
    async verb10(requestParameters: Verb10Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TripList> {
        const response = await this.verb10Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const Verb10FormatEnum = {
    Xml: 'xml',
    Json: 'json',
    Jsonp: 'jsonp'
} as const;
export type Verb10FormatEnum = typeof Verb10FormatEnum[keyof typeof Verb10FormatEnum];
/**
 * @export
 */
export const Verb10PolyEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10PolyEnum = typeof Verb10PolyEnum[keyof typeof Verb10PolyEnum];
/**
 * @export
 */
export const Verb10PolyEncEnum = {
    Dlt: 'DLT',
    Gpa: 'GPA',
    N: 'N'
} as const;
export type Verb10PolyEncEnum = typeof Verb10PolyEncEnum[keyof typeof Verb10PolyEncEnum];
/**
 * @export
 */
export const Verb10UseCombinedComparisonEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10UseCombinedComparisonEnum = typeof Verb10UseCombinedComparisonEnum[keyof typeof Verb10UseCombinedComparisonEnum];
/**
 * @export
 */
export const Verb10AcceptGapsEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10AcceptGapsEnum = typeof Verb10AcceptGapsEnum[keyof typeof Verb10AcceptGapsEnum];
/**
 * @export
 */
export const Verb10AllowDummySectionsEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10AllowDummySectionsEnum = typeof Verb10AllowDummySectionsEnum[keyof typeof Verb10AllowDummySectionsEnum];
/**
 * @export
 */
export const Verb10FlagAllNonReachableEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10FlagAllNonReachableEnum = typeof Verb10FlagAllNonReachableEnum[keyof typeof Verb10FlagAllNonReachableEnum];
/**
 * @export
 */
export const Verb10MatchCatStrictEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10MatchCatStrictEnum = typeof Verb10MatchCatStrictEnum[keyof typeof Verb10MatchCatStrictEnum];
/**
 * @export
 */
export const Verb10MatchIdNonBlankEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10MatchIdNonBlankEnum = typeof Verb10MatchIdNonBlankEnum[keyof typeof Verb10MatchIdNonBlankEnum];
/**
 * @export
 */
export const Verb10MatchIdStrictEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10MatchIdStrictEnum = typeof Verb10MatchIdStrictEnum[keyof typeof Verb10MatchIdStrictEnum];
/**
 * @export
 */
export const Verb10MatchNumStrictEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10MatchNumStrictEnum = typeof Verb10MatchNumStrictEnum[keyof typeof Verb10MatchNumStrictEnum];
/**
 * @export
 */
export const Verb10MatchRtTypeEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10MatchRtTypeEnum = typeof Verb10MatchRtTypeEnum[keyof typeof Verb10MatchRtTypeEnum];
/**
 * @export
 */
export const Verb10EnableRtFullSearchEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10EnableRtFullSearchEnum = typeof Verb10EnableRtFullSearchEnum[keyof typeof Verb10EnableRtFullSearchEnum];
/**
 * @export
 */
export const Verb10EnableReplacementsEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10EnableReplacementsEnum = typeof Verb10EnableReplacementsEnum[keyof typeof Verb10EnableReplacementsEnum];
/**
 * @export
 */
export const Verb10PasslistEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10PasslistEnum = typeof Verb10PasslistEnum[keyof typeof Verb10PasslistEnum];
/**
 * @export
 */
export const Verb10ShowPassingPointsEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10ShowPassingPointsEnum = typeof Verb10ShowPassingPointsEnum[keyof typeof Verb10ShowPassingPointsEnum];
/**
 * @export
 */
export const Verb10RtModeEnum = {
    Full: 'FULL',
    Infos: 'INFOS',
    Off: 'OFF',
    Realtime: 'REALTIME',
    ServerDefault: 'SERVER_DEFAULT'
} as const;
export type Verb10RtModeEnum = typeof Verb10RtModeEnum[keyof typeof Verb10RtModeEnum];
/**
 * @export
 */
export const Verb10EcoEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10EcoEnum = typeof Verb10EcoEnum[keyof typeof Verb10EcoEnum];
/**
 * @export
 */
export const Verb10EcoCmpEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10EcoCmpEnum = typeof Verb10EcoCmpEnum[keyof typeof Verb10EcoCmpEnum];
/**
 * @export
 */
export const Verb10TariffEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10TariffEnum = typeof Verb10TariffEnum[keyof typeof Verb10TariffEnum];
/**
 * @export
 */
export const Verb10TrafficMessagesEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10TrafficMessagesEnum = typeof Verb10TrafficMessagesEnum[keyof typeof Verb10TrafficMessagesEnum];
/**
 * @export
 */
export const Verb10WithJourneyBoundaryPointsEnum = {
    _0: '0',
    _1: '1'
} as const;
export type Verb10WithJourneyBoundaryPointsEnum = typeof Verb10WithJourneyBoundaryPointsEnum[keyof typeof Verb10WithJourneyBoundaryPointsEnum];
