name: Generate client
on:
  push:
    paths:
      - ".github/workflows/generate-client.yml"
permissions:
  contents: write
jobs:
  generate-clients:
    runs-on: ubuntu-latest
    name: Generate client
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cleanup old client
      run: rm -rf typescript-fetch-client/

    - name: Generate new client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: typescript-fetch
        openapi-url: https://routenplaner.verkehrsauskunft.at/vao/restproxy/v1.8.0/api-doc

    - name: Commit new client
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Generate client

    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - run: git config --global user.name 'CI'
    - run: git config --global user.email 'github-ci@robs.social'
    - run: npm version minor
    - run: git push && git push --tags
