name: Generate client
on: push
permissions:
  contents: write
jobs:
  generate-clients:
    runs-on: ubuntu-latest
    name: Generate client
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cleanup old client
      run: rm -rf typescript-fetch-client/

    - name: Generate new client
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: typescript-fetch
        openapi-url: https://routenplaner.verkehrsauskunft.at/vao/restproxy/v1.8.0/api-doc

    - name: Commit new client
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Generate client
