/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StopLocation } from './StopLocation';
import {
    StopLocationFromJSON,
    StopLocationFromJSONTyped,
    StopLocationToJSON,
} from './StopLocation';

/**
 * 
 * @export
 * @interface AffectedStopType
 */
export interface AffectedStopType {
    /**
     * 
     * @type {Array<StopLocation>}
     * @memberof AffectedStopType
     */
    readonly stopLocation: Array<StopLocation>;
}

/**
 * Check if a given object implements the AffectedStopType interface.
 */
export function instanceOfAffectedStopType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stopLocation" in value;

    return isInstance;
}

export function AffectedStopTypeFromJSON(json: any): AffectedStopType {
    return AffectedStopTypeFromJSONTyped(json, false);
}

export function AffectedStopTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffectedStopType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stopLocation': ((json['StopLocation'] as Array<any>).map(StopLocationFromJSON)),
    };
}

export function AffectedStopTypeToJSON(value?: AffectedStopType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

