/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MapInfoType } from './MapInfoType';
import {
    MapInfoTypeFromJSON,
    MapInfoTypeFromJSONTyped,
    MapInfoTypeToJSON,
} from './MapInfoType';
import type { MobilityServiceProviderInfoType } from './MobilityServiceProviderInfoType';
import {
    MobilityServiceProviderInfoTypeFromJSON,
    MobilityServiceProviderInfoTypeFromJSONTyped,
    MobilityServiceProviderInfoTypeToJSON,
} from './MobilityServiceProviderInfoType';
import type { OperatorType } from './OperatorType';
import {
    OperatorTypeFromJSON,
    OperatorTypeFromJSONTyped,
    OperatorTypeToJSON,
} from './OperatorType';
import type { ProductCategoryType } from './ProductCategoryType';
import {
    ProductCategoryTypeFromJSON,
    ProductCategoryTypeFromJSONTyped,
    ProductCategoryTypeToJSON,
} from './ProductCategoryType';
import type { ProductType } from './ProductType';
import {
    ProductTypeFromJSON,
    ProductTypeFromJSONTyped,
    ProductTypeToJSON,
} from './ProductType';
import type { RegionType } from './RegionType';
import {
    RegionTypeFromJSON,
    RegionTypeFromJSONTyped,
    RegionTypeToJSON,
} from './RegionType';
import type { TechnicalMessages } from './TechnicalMessages';
import {
    TechnicalMessagesFromJSON,
    TechnicalMessagesFromJSONTyped,
    TechnicalMessagesToJSON,
} from './TechnicalMessages';
import type { Warnings } from './Warnings';
import {
    WarningsFromJSON,
    WarningsFromJSONTyped,
    WarningsToJSON,
} from './Warnings';

/**
 * 
 * @export
 * @interface DataInfo
 */
export interface DataInfo {
    /**
     * 
     * @type {TechnicalMessages}
     * @memberof DataInfo
     */
    technicalMessages?: TechnicalMessages;
    /**
     * 
     * @type {Warnings}
     * @memberof DataInfo
     */
    warnings?: Warnings;
    /**
     * 
     * @type {string}
     * @memberof DataInfo
     */
    serverVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof DataInfo
     */
    dialectVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof DataInfo
     */
    version?: string;
    /**
     * 
     * @type {Date}
     * @memberof DataInfo
     */
    planRtTs?: Date;
    /**
     * 
     * @type {string}
     * @memberof DataInfo
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof DataInfo
     */
    errorText?: string;
    /**
     * 
     * @type {string}
     * @memberof DataInfo
     */
    requestId?: string;
    /**
     * 
     * @type {Array<OperatorType>}
     * @memberof DataInfo
     */
    operator?: Array<OperatorType>;
    /**
     * 
     * @type {Array<ProductType>}
     * @memberof DataInfo
     */
    product?: Array<ProductType>;
    /**
     * 
     * @type {Array<ProductCategoryType>}
     * @memberof DataInfo
     */
    productCategory?: Array<ProductCategoryType>;
    /**
     * 
     * @type {Array<RegionType>}
     * @memberof DataInfo
     */
    region?: Array<RegionType>;
    /**
     * 
     * @type {Array<MapInfoType>}
     * @memberof DataInfo
     */
    mapInfo?: Array<MapInfoType>;
    /**
     * 
     * @type {Array<MobilityServiceProviderInfoType>}
     * @memberof DataInfo
     */
    mobilityServiceProviderInfo?: Array<MobilityServiceProviderInfoType>;
    /**
     * 
     * @type {string}
     * @memberof DataInfo
     */
    begin?: string;
    /**
     * 
     * @type {string}
     * @memberof DataInfo
     */
    end?: string;
}

/**
 * Check if a given object implements the DataInfo interface.
 */
export function instanceOfDataInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DataInfoFromJSON(json: any): DataInfo {
    return DataInfoFromJSONTyped(json, false);
}

export function DataInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'technicalMessages': !exists(json, 'TechnicalMessages') ? undefined : TechnicalMessagesFromJSON(json['TechnicalMessages']),
        'warnings': !exists(json, 'Warnings') ? undefined : WarningsFromJSON(json['Warnings']),
        'serverVersion': !exists(json, 'serverVersion') ? undefined : json['serverVersion'],
        'dialectVersion': !exists(json, 'dialectVersion') ? undefined : json['dialectVersion'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'planRtTs': !exists(json, 'planRtTs') ? undefined : (new Date(json['planRtTs'])),
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
        'errorText': !exists(json, 'errorText') ? undefined : json['errorText'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'operator': !exists(json, 'Operator') ? undefined : ((json['Operator'] as Array<any>).map(OperatorTypeFromJSON)),
        'product': !exists(json, 'Product') ? undefined : ((json['Product'] as Array<any>).map(ProductTypeFromJSON)),
        'productCategory': !exists(json, 'ProductCategory') ? undefined : ((json['ProductCategory'] as Array<any>).map(ProductCategoryTypeFromJSON)),
        'region': !exists(json, 'Region') ? undefined : ((json['Region'] as Array<any>).map(RegionTypeFromJSON)),
        'mapInfo': !exists(json, 'MapInfo') ? undefined : ((json['MapInfo'] as Array<any>).map(MapInfoTypeFromJSON)),
        'mobilityServiceProviderInfo': !exists(json, 'MobilityServiceProviderInfo') ? undefined : ((json['MobilityServiceProviderInfo'] as Array<any>).map(MobilityServiceProviderInfoTypeFromJSON)),
        'begin': !exists(json, 'begin') ? undefined : json['begin'],
        'end': !exists(json, 'end') ? undefined : json['end'],
    };
}

export function DataInfoToJSON(value?: DataInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TechnicalMessages': TechnicalMessagesToJSON(value.technicalMessages),
        'Warnings': WarningsToJSON(value.warnings),
        'serverVersion': value.serverVersion,
        'dialectVersion': value.dialectVersion,
        'version': value.version,
        'planRtTs': value.planRtTs === undefined ? undefined : (value.planRtTs.toISOString()),
        'errorCode': value.errorCode,
        'errorText': value.errorText,
        'requestId': value.requestId,
        'Operator': value.operator === undefined ? undefined : ((value.operator as Array<any>).map(OperatorTypeToJSON)),
        'Product': value.product === undefined ? undefined : ((value.product as Array<any>).map(ProductTypeToJSON)),
        'ProductCategory': value.productCategory === undefined ? undefined : ((value.productCategory as Array<any>).map(ProductCategoryTypeToJSON)),
        'Region': value.region === undefined ? undefined : ((value.region as Array<any>).map(RegionTypeToJSON)),
        'MapInfo': value.mapInfo === undefined ? undefined : ((value.mapInfo as Array<any>).map(MapInfoTypeToJSON)),
        'MobilityServiceProviderInfo': value.mobilityServiceProviderInfo === undefined ? undefined : ((value.mobilityServiceProviderInfo as Array<any>).map(MobilityServiceProviderInfoTypeToJSON)),
        'begin': value.begin,
        'end': value.end,
    };
}

