/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Direction } from './Direction';
import {
    DirectionFromJSON,
    DirectionFromJSONTyped,
    DirectionToJSON,
} from './Direction';

/**
 * 
 * @export
 * @interface Directions
 */
export interface Directions {
    /**
     * 
     * @type {Array<Direction>}
     * @memberof Directions
     */
    direction: Array<Direction>;
}

/**
 * Check if a given object implements the Directions interface.
 */
export function instanceOfDirections(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "direction" in value;

    return isInstance;
}

export function DirectionsFromJSON(json: any): Directions {
    return DirectionsFromJSONTyped(json, false);
}

export function DirectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Directions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'direction': ((json['Direction'] as Array<any>).map(DirectionFromJSON)),
    };
}

export function DirectionsToJSON(value?: Directions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Direction': ((value.direction as Array<any>).map(DirectionToJSON)),
    };
}

