/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FareItem } from './FareItem';
import {
    FareItemFromJSON,
    FareItemFromJSONTyped,
    FareItemToJSON,
} from './FareItem';
import type { KVType } from './KVType';
import {
    KVTypeFromJSON,
    KVTypeFromJSONTyped,
    KVTypeToJSON,
} from './KVType';

/**
 * 
 * @export
 * @interface FareSetItem
 */
export interface FareSetItem {
    /**
     * 
     * @type {Array<FareItem>}
     * @memberof FareSetItem
     */
    readonly fareItem?: Array<FareItem>;
    /**
     * 
     * @type {Array<KVType>}
     * @memberof FareSetItem
     */
    readonly param?: Array<KVType>;
    /**
     * 
     * @type {string}
     * @memberof FareSetItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FareSetItem
     */
    desc?: string;
    /**
     * 
     * @type {number}
     * @memberof FareSetItem
     */
    fromLeg?: number;
    /**
     * 
     * @type {number}
     * @memberof FareSetItem
     */
    toLeg?: number;
    /**
     * 
     * @type {string}
     * @memberof FareSetItem
     */
    fromLegId?: string;
    /**
     * 
     * @type {string}
     * @memberof FareSetItem
     */
    toLegId?: string;
}

/**
 * Check if a given object implements the FareSetItem interface.
 */
export function instanceOfFareSetItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FareSetItemFromJSON(json: any): FareSetItem {
    return FareSetItemFromJSONTyped(json, false);
}

export function FareSetItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FareSetItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fareItem': !exists(json, 'fareItem') ? undefined : ((json['fareItem'] as Array<any>).map(FareItemFromJSON)),
        'param': !exists(json, 'param') ? undefined : ((json['param'] as Array<any>).map(KVTypeFromJSON)),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'desc': !exists(json, 'desc') ? undefined : json['desc'],
        'fromLeg': !exists(json, 'fromLeg') ? undefined : json['fromLeg'],
        'toLeg': !exists(json, 'toLeg') ? undefined : json['toLeg'],
        'fromLegId': !exists(json, 'fromLegId') ? undefined : json['fromLegId'],
        'toLegId': !exists(json, 'toLegId') ? undefined : json['toLegId'],
    };
}

export function FareSetItemToJSON(value?: FareSetItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'desc': value.desc,
        'fromLeg': value.fromLeg,
        'toLeg': value.toLeg,
        'fromLegId': value.fromLegId,
        'toLegId': value.toLegId,
    };
}

