/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GisEdgeType
 */
export interface GisEdgeType {
    /**
     * 
     * @type {string}
     * @memberof GisEdgeType
     */
    edgeId?: string;
    /**
     * 
     * @type {string}
     * @memberof GisEdgeType
     */
    graphId?: string;
}

/**
 * Check if a given object implements the GisEdgeType interface.
 */
export function instanceOfGisEdgeType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GisEdgeTypeFromJSON(json: any): GisEdgeType {
    return GisEdgeTypeFromJSONTyped(json, false);
}

export function GisEdgeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GisEdgeType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edgeId': !exists(json, 'edgeId') ? undefined : json['edgeId'],
        'graphId': !exists(json, 'graphId') ? undefined : json['graphId'],
    };
}

export function GisEdgeTypeToJSON(value?: GisEdgeType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edgeId': value.edgeId,
        'graphId': value.graphId,
    };
}

