/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';
import type { TechnicalMessages } from './TechnicalMessages';
import {
    TechnicalMessagesFromJSON,
    TechnicalMessagesFromJSONTyped,
    TechnicalMessagesToJSON,
} from './TechnicalMessages';
import type { Warnings } from './Warnings';
import {
    WarningsFromJSON,
    WarningsFromJSONTyped,
    WarningsToJSON,
} from './Warnings';

/**
 * 
 * @export
 * @interface HimMessages
 */
export interface HimMessages {
    /**
     * 
     * @type {TechnicalMessages}
     * @memberof HimMessages
     */
    technicalMessages?: TechnicalMessages;
    /**
     * 
     * @type {Warnings}
     * @memberof HimMessages
     */
    warnings?: Warnings;
    /**
     * 
     * @type {string}
     * @memberof HimMessages
     */
    serverVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof HimMessages
     */
    dialectVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof HimMessages
     */
    version?: string;
    /**
     * 
     * @type {Date}
     * @memberof HimMessages
     */
    planRtTs?: Date;
    /**
     * 
     * @type {string}
     * @memberof HimMessages
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof HimMessages
     */
    errorText?: string;
    /**
     * 
     * @type {string}
     * @memberof HimMessages
     */
    requestId?: string;
    /**
     * 
     * @type {Array<Message>}
     * @memberof HimMessages
     */
    message?: Array<Message>;
}

/**
 * Check if a given object implements the HimMessages interface.
 */
export function instanceOfHimMessages(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HimMessagesFromJSON(json: any): HimMessages {
    return HimMessagesFromJSONTyped(json, false);
}

export function HimMessagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): HimMessages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'technicalMessages': !exists(json, 'TechnicalMessages') ? undefined : TechnicalMessagesFromJSON(json['TechnicalMessages']),
        'warnings': !exists(json, 'Warnings') ? undefined : WarningsFromJSON(json['Warnings']),
        'serverVersion': !exists(json, 'serverVersion') ? undefined : json['serverVersion'],
        'dialectVersion': !exists(json, 'dialectVersion') ? undefined : json['dialectVersion'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'planRtTs': !exists(json, 'planRtTs') ? undefined : (new Date(json['planRtTs'])),
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
        'errorText': !exists(json, 'errorText') ? undefined : json['errorText'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'message': !exists(json, 'Message') ? undefined : ((json['Message'] as Array<any>).map(MessageFromJSON)),
    };
}

export function HimMessagesToJSON(value?: HimMessages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TechnicalMessages': TechnicalMessagesToJSON(value.technicalMessages),
        'Warnings': WarningsToJSON(value.warnings),
        'serverVersion': value.serverVersion,
        'dialectVersion': value.dialectVersion,
        'version': value.version,
        'planRtTs': value.planRtTs === undefined ? undefined : (value.planRtTs.toISOString()),
        'errorCode': value.errorCode,
        'errorText': value.errorText,
        'requestId': value.requestId,
        'Message': value.message === undefined ? undefined : ((value.message as Array<any>).map(MessageToJSON)),
    };
}

