/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JourneyDetailRef
 */
export interface JourneyDetailRef {
    /**
     * 
     * @type {string}
     * @memberof JourneyDetailRef
     */
    ref: string;
}

/**
 * Check if a given object implements the JourneyDetailRef interface.
 */
export function instanceOfJourneyDetailRef(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ref" in value;

    return isInstance;
}

export function JourneyDetailRefFromJSON(json: any): JourneyDetailRef {
    return JourneyDetailRefFromJSONTyped(json, false);
}

export function JourneyDetailRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyDetailRef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ref': json['ref'],
    };
}

export function JourneyDetailRefToJSON(value?: JourneyDetailRef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ref': value.ref,
    };
}

