/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KVType
 */
export interface KVType {
    /**
     * 
     * @type {string}
     * @memberof KVType
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof KVType
     */
    value?: string;
}

/**
 * Check if a given object implements the KVType interface.
 */
export function instanceOfKVType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function KVTypeFromJSON(json: any): KVType {
    return KVTypeFromJSONTyped(json, false);
}

export function KVTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): KVType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function KVTypeToJSON(value?: KVType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
    };
}

