/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationNote } from './LocationNote';
import {
    LocationNoteFromJSON,
    LocationNoteFromJSONTyped,
    LocationNoteToJSON,
} from './LocationNote';

/**
 * 
 * @export
 * @interface LocationNotes
 */
export interface LocationNotes {
    /**
     * 
     * @type {Array<LocationNote>}
     * @memberof LocationNotes
     */
    locationNote: Array<LocationNote>;
}

/**
 * Check if a given object implements the LocationNotes interface.
 */
export function instanceOfLocationNotes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "locationNote" in value;

    return isInstance;
}

export function LocationNotesFromJSON(json: any): LocationNotes {
    return LocationNotesFromJSONTyped(json, false);
}

export function LocationNotesFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationNotes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'locationNote': ((json['LocationNote'] as Array<any>).map(LocationNoteFromJSON)),
    };
}

export function LocationNotesToJSON(value?: LocationNotes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'LocationNote': ((value.locationNote as Array<any>).map(LocationNoteToJSON)),
    };
}

