/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 
 * @export
 * @interface Messages
 */
export interface Messages {
    /**
     * 
     * @type {Array<Message>}
     * @memberof Messages
     */
    message: Array<Message>;
}

/**
 * Check if a given object implements the Messages interface.
 */
export function instanceOfMessages(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function MessagesFromJSON(json: any): Messages {
    return MessagesFromJSONTyped(json, false);
}

export function MessagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Messages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': ((json['Message'] as Array<any>).map(MessageFromJSON)),
    };
}

export function MessagesToJSON(value?: Messages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Message': ((value.message as Array<any>).map(MessageToJSON)),
    };
}

