/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinate } from './Coordinate';
import {
    CoordinateFromJSON,
    CoordinateFromJSONTyped,
    CoordinateToJSON,
} from './Coordinate';
import type { Polyline } from './Polyline';
import {
    PolylineFromJSON,
    PolylineFromJSONTyped,
    PolylineToJSON,
} from './Polyline';
import type { PolylineGroup } from './PolylineGroup';
import {
    PolylineGroupFromJSON,
    PolylineGroupFromJSONTyped,
    PolylineGroupToJSON,
} from './PolylineGroup';
import type { Ring } from './Ring';
import {
    RingFromJSON,
    RingFromJSONTyped,
    RingToJSON,
} from './Ring';

/**
 * 
 * @export
 * @interface MessageRegionType
 */
export interface MessageRegionType {
    /**
     * 
     * @type {string}
     * @memberof MessageRegionType
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageRegionType
     */
    id?: string;
    /**
     * 
     * @type {Array<Polyline>}
     * @memberof MessageRegionType
     */
    readonly polyline?: Array<Polyline>;
    /**
     * 
     * @type {PolylineGroup}
     * @memberof MessageRegionType
     */
    polylineGroup?: PolylineGroup;
    /**
     * 
     * @type {Coordinate}
     * @memberof MessageRegionType
     */
    iconCoordinate?: Coordinate;
    /**
     * 
     * @type {Ring}
     * @memberof MessageRegionType
     */
    ring?: Ring;
    /**
     * 
     * @type {Array<number>}
     * @memberof MessageRegionType
     */
    readonly messageRef?: Array<number>;
}

/**
 * Check if a given object implements the MessageRegionType interface.
 */
export function instanceOfMessageRegionType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MessageRegionTypeFromJSON(json: any): MessageRegionType {
    return MessageRegionTypeFromJSONTyped(json, false);
}

export function MessageRegionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageRegionType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'polyline': !exists(json, 'polyline') ? undefined : ((json['polyline'] as Array<any>).map(PolylineFromJSON)),
        'polylineGroup': !exists(json, 'polylineGroup') ? undefined : PolylineGroupFromJSON(json['polylineGroup']),
        'iconCoordinate': !exists(json, 'iconCoordinate') ? undefined : CoordinateFromJSON(json['iconCoordinate']),
        'ring': !exists(json, 'ring') ? undefined : RingFromJSON(json['ring']),
        'messageRef': !exists(json, 'messageRef') ? undefined : json['messageRef'],
    };
}

export function MessageRegionTypeToJSON(value?: MessageRegionType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'id': value.id,
        'polylineGroup': PolylineGroupToJSON(value.polylineGroup),
        'iconCoordinate': CoordinateToJSON(value.iconCoordinate),
        'ring': RingToJSON(value.ring),
    };
}

