/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageCategoryType
 */
export interface MessageCategoryType {
    /**
     * 
     * @type {number}
     * @memberof MessageCategoryType
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MessageCategoryType
     */
    name?: string;
}

/**
 * Check if a given object implements the MessageCategoryType interface.
 */
export function instanceOfMessageCategoryType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function MessageCategoryTypeFromJSON(json: any): MessageCategoryType {
    return MessageCategoryTypeFromJSONTyped(json, false);
}

export function MessageCategoryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageCategoryType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function MessageCategoryTypeToJSON(value?: MessageCategoryType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

