/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MobilityServiceProviderInfoType
 */
export interface MobilityServiceProviderInfoType {
    /**
     * 
     * @type {string}
     * @memberof MobilityServiceProviderInfoType
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MobilityServiceProviderInfoType
     */
    extId?: string;
    /**
     * 
     * @type {string}
     * @memberof MobilityServiceProviderInfoType
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MobilityServiceProviderInfoType
     */
    nameS?: string;
    /**
     * 
     * @type {string}
     * @memberof MobilityServiceProviderInfoType
     */
    abbreviation?: string;
}

/**
 * Check if a given object implements the MobilityServiceProviderInfoType interface.
 */
export function instanceOfMobilityServiceProviderInfoType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MobilityServiceProviderInfoTypeFromJSON(json: any): MobilityServiceProviderInfoType {
    return MobilityServiceProviderInfoTypeFromJSONTyped(json, false);
}

export function MobilityServiceProviderInfoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MobilityServiceProviderInfoType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'extId': !exists(json, 'extId') ? undefined : json['extId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'nameS': !exists(json, 'nameS') ? undefined : json['nameS'],
        'abbreviation': !exists(json, 'abbreviation') ? undefined : json['abbreviation'],
    };
}

export function MobilityServiceProviderInfoTypeToJSON(value?: MobilityServiceProviderInfoType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'extId': value.extId,
        'name': value.name,
        'nameS': value.nameS,
        'abbreviation': value.abbreviation,
    };
}

