/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Note } from './Note';
import {
    NoteFromJSON,
    NoteFromJSONTyped,
    NoteToJSON,
} from './Note';

/**
 * 
 * @export
 * @interface Notes
 */
export interface Notes {
    /**
     * 
     * @type {Array<Note>}
     * @memberof Notes
     */
    note: Array<Note>;
}

/**
 * Check if a given object implements the Notes interface.
 */
export function instanceOfNotes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "note" in value;

    return isInstance;
}

export function NotesFromJSON(json: any): Notes {
    return NotesFromJSONTyped(json, false);
}

export function NotesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'note': ((json['Note'] as Array<any>).map(NoteFromJSON)),
    };
}

export function NotesToJSON(value?: Notes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Note': ((value.note as Array<any>).map(NoteToJSON)),
    };
}

