/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Note
 */
export interface Note {
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    type?: NoteTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    priority?: number;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    routeIdxFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof Note
     */
    routeIdxTo?: number;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    txtN?: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    txtL?: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    txtS?: string;
}


/**
 * @export
 */
export const NoteTypeEnum = {
    U: 'U',
    A: 'A',
    I: 'I',
    R: 'R',
    H: 'H',
    M: 'M',
    C: 'C',
    D: 'D',
    B: 'B',
    Q: 'Q',
    L: 'L',
    N: 'N',
    O: 'O',
    P: 'P',
    S: 'S',
    V: 'V',
    X: 'X',
    Z: 'Z',
    Y: 'Y',
    K: 'K',
    G: 'G',
    W: 'W',
    Ed: 'ED',
    Tar: 'TAR',
    Fn: 'FN',
    Tln: 'TLN',
    Lnc: 'LNC'
} as const;
export type NoteTypeEnum = typeof NoteTypeEnum[keyof typeof NoteTypeEnum];


/**
 * Check if a given object implements the Note interface.
 */
export function instanceOfNote(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NoteFromJSON(json: any): Note {
    return NoteFromJSONTyped(json, false);
}

export function NoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Note {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'key': !exists(json, 'key') ? undefined : json['key'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'priority': !exists(json, 'priority') ? undefined : json['priority'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'routeIdxFrom': !exists(json, 'routeIdxFrom') ? undefined : json['routeIdxFrom'],
        'routeIdxTo': !exists(json, 'routeIdxTo') ? undefined : json['routeIdxTo'],
        'txtN': !exists(json, 'txtN') ? undefined : json['txtN'],
        'txtL': !exists(json, 'txtL') ? undefined : json['txtL'],
        'txtS': !exists(json, 'txtS') ? undefined : json['txtS'],
    };
}

export function NoteToJSON(value?: Note | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'key': value.key,
        'type': value.type,
        'priority': value.priority,
        'url': value.url,
        'routeIdxFrom': value.routeIdxFrom,
        'routeIdxTo': value.routeIdxTo,
        'txtN': value.txtN,
        'txtL': value.txtL,
        'txtS': value.txtS,
    };
}

