/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OccupancyType
 */
export interface OccupancyType {
    /**
     * 
     * @type {string}
     * @memberof OccupancyType
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof OccupancyType
     */
    v?: number;
    /**
     * 
     * @type {string}
     * @memberof OccupancyType
     */
    number?: string;
    /**
     * 
     * @type {number}
     * @memberof OccupancyType
     */
    raw?: number;
}

/**
 * Check if a given object implements the OccupancyType interface.
 */
export function instanceOfOccupancyType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OccupancyTypeFromJSON(json: any): OccupancyType {
    return OccupancyTypeFromJSONTyped(json, false);
}

export function OccupancyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OccupancyType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'v': !exists(json, 'v') ? undefined : json['v'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'raw': !exists(json, 'raw') ? undefined : json['raw'],
    };
}

export function OccupancyTypeToJSON(value?: OccupancyType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'v': value.v,
        'number': value.number,
        'raw': value.raw,
    };
}

