/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PricingType
 */
export interface PricingType {
    /**
     * 
     * @type {object}
     * @memberof PricingType
     */
    any?: object;
    /**
     * 
     * @type {number}
     * @memberof PricingType
     */
    idx: number;
}

/**
 * Check if a given object implements the PricingType interface.
 */
export function instanceOfPricingType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "idx" in value;

    return isInstance;
}

export function PricingTypeFromJSON(json: any): PricingType {
    return PricingTypeFromJSONTyped(json, false);
}

export function PricingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'any': !exists(json, 'any') ? undefined : json['any'],
        'idx': json['idx'],
    };
}

export function PricingTypeToJSON(value?: PricingType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'any': value.any,
        'idx': value.idx,
    };
}

