/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductType } from './ProductType';
import {
    ProductTypeFromJSON,
    ProductTypeFromJSONTyped,
    ProductTypeToJSON,
} from './ProductType';

/**
 * 
 * @export
 * @interface ProductCategoryType
 */
export interface ProductCategoryType {
    /**
     * 
     * @type {Array<ProductType>}
     * @memberof ProductCategoryType
     */
    product?: Array<ProductType>;
    /**
     * 
     * @type {string}
     * @memberof ProductCategoryType
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCategoryType
     */
    cls?: string;
}

/**
 * Check if a given object implements the ProductCategoryType interface.
 */
export function instanceOfProductCategoryType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ProductCategoryTypeFromJSON(json: any): ProductCategoryType {
    return ProductCategoryTypeFromJSONTyped(json, false);
}

export function ProductCategoryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCategoryType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'product': !exists(json, 'Product') ? undefined : ((json['Product'] as Array<any>).map(ProductTypeFromJSON)),
        'name': json['name'],
        'cls': !exists(json, 'cls') ? undefined : json['cls'],
    };
}

export function ProductCategoryTypeToJSON(value?: ProductCategoryType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Product': value.product === undefined ? undefined : ((value.product as Array<any>).map(ProductTypeToJSON)),
        'name': value.name,
        'cls': value.cls,
    };
}

