/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinate } from './Coordinate';
import {
    CoordinateFromJSON,
    CoordinateFromJSONTyped,
    CoordinateToJSON,
} from './Coordinate';

/**
 * 
 * @export
 * @interface Rect
 */
export interface Rect {
    /**
     * 
     * @type {Coordinate}
     * @memberof Rect
     */
    llCrd: Coordinate;
    /**
     * 
     * @type {Coordinate}
     * @memberof Rect
     */
    urCrd: Coordinate;
}

/**
 * Check if a given object implements the Rect interface.
 */
export function instanceOfRect(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "llCrd" in value;
    isInstance = isInstance && "urCrd" in value;

    return isInstance;
}

export function RectFromJSON(json: any): Rect {
    return RectFromJSONTyped(json, false);
}

export function RectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rect {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'llCrd': CoordinateFromJSON(json['llCrd']),
        'urCrd': CoordinateFromJSON(json['urCrd']),
    };
}

export function RectToJSON(value?: Rect | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'llCrd': CoordinateToJSON(value.llCrd),
        'urCrd': CoordinateToJSON(value.urCrd),
    };
}

