/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegionType
 */
export interface RegionType {
    /**
     * 
     * @type {string}
     * @memberof RegionType
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof RegionType
     */
    extId: number;
}

/**
 * Check if a given object implements the RegionType interface.
 */
export function instanceOfRegionType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "extId" in value;

    return isInstance;
}

export function RegionTypeFromJSON(json: any): RegionType {
    return RegionTypeFromJSONTyped(json, false);
}

export function RegionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegionType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'extId': json['extId'],
    };
}

export function RegionTypeToJSON(value?: RegionType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'extId': value.extId,
    };
}

