/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceLinkType
 */
export interface ResourceLinkType {
    /**
     * 
     * @type {string}
     * @memberof ResourceLinkType
     */
    rel: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceLinkType
     */
    href: string;
}

/**
 * Check if a given object implements the ResourceLinkType interface.
 */
export function instanceOfResourceLinkType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rel" in value;
    isInstance = isInstance && "href" in value;

    return isInstance;
}

export function ResourceLinkTypeFromJSON(json: any): ResourceLinkType {
    return ResourceLinkTypeFromJSONTyped(json, false);
}

export function ResourceLinkTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceLinkType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rel': json['rel'],
        'href': json['href'],
    };
}

export function ResourceLinkTypeToJSON(value?: ResourceLinkType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rel': value.rel,
        'href': value.href,
    };
}

