/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceLinkType } from './ResourceLinkType';
import {
    ResourceLinkTypeFromJSON,
    ResourceLinkTypeFromJSONTyped,
    ResourceLinkTypeToJSON,
} from './ResourceLinkType';

/**
 * 
 * @export
 * @interface ResourceLinks
 */
export interface ResourceLinks {
    /**
     * 
     * @type {Array<ResourceLinkType>}
     * @memberof ResourceLinks
     */
    readonly link?: Array<ResourceLinkType>;
}

/**
 * Check if a given object implements the ResourceLinks interface.
 */
export function instanceOfResourceLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResourceLinksFromJSON(json: any): ResourceLinks {
    return ResourceLinksFromJSONTyped(json, false);
}

export function ResourceLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'link': !exists(json, 'link') ? undefined : ((json['link'] as Array<any>).map(ResourceLinkTypeFromJSON)),
    };
}

export function ResourceLinksToJSON(value?: ResourceLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

