/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ring
 */
export interface Ring {
    /**
     * 
     * @type {number}
     * @memberof Ring
     */
    lon: number;
    /**
     * 
     * @type {number}
     * @memberof Ring
     */
    lat: number;
    /**
     * 
     * @type {number}
     * @memberof Ring
     */
    minRadius?: number;
    /**
     * 
     * @type {number}
     * @memberof Ring
     */
    maxRadius?: number;
}

/**
 * Check if a given object implements the Ring interface.
 */
export function instanceOfRing(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lon" in value;
    isInstance = isInstance && "lat" in value;

    return isInstance;
}

export function RingFromJSON(json: any): Ring {
    return RingFromJSONTyped(json, false);
}

export function RingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ring {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lon': json['lon'],
        'lat': json['lat'],
        'minRadius': !exists(json, 'minRadius') ? undefined : json['minRadius'],
        'maxRadius': !exists(json, 'maxRadius') ? undefined : json['maxRadius'],
    };
}

export function RingToJSON(value?: Ring | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lon': value.lon,
        'lat': value.lat,
        'minRadius': value.minRadius,
        'maxRadius': value.maxRadius,
    };
}

