/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceDays
 */
export interface ServiceDays {
    /**
     * 
     * @type {string}
     * @memberof ServiceDays
     */
    planningPeriodBegin?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDays
     */
    planningPeriodEnd?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDays
     */
    sDaysR?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDays
     */
    sDaysI?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDays
     */
    sDaysB?: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceDays
     */
    routeIdxFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceDays
     */
    routeIdxTo?: number;
}

/**
 * Check if a given object implements the ServiceDays interface.
 */
export function instanceOfServiceDays(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServiceDaysFromJSON(json: any): ServiceDays {
    return ServiceDaysFromJSONTyped(json, false);
}

export function ServiceDaysFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceDays {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'planningPeriodBegin': !exists(json, 'planningPeriodBegin') ? undefined : json['planningPeriodBegin'],
        'planningPeriodEnd': !exists(json, 'planningPeriodEnd') ? undefined : json['planningPeriodEnd'],
        'sDaysR': !exists(json, 'sDaysR') ? undefined : json['sDaysR'],
        'sDaysI': !exists(json, 'sDaysI') ? undefined : json['sDaysI'],
        'sDaysB': !exists(json, 'sDaysB') ? undefined : json['sDaysB'],
        'routeIdxFrom': !exists(json, 'routeIdxFrom') ? undefined : json['routeIdxFrom'],
        'routeIdxTo': !exists(json, 'routeIdxTo') ? undefined : json['routeIdxTo'],
    };
}

export function ServiceDaysToJSON(value?: ServiceDays | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'planningPeriodBegin': value.planningPeriodBegin,
        'planningPeriodEnd': value.planningPeriodEnd,
        'sDaysR': value.sDaysR,
        'sDaysI': value.sDaysI,
        'sDaysB': value.sDaysB,
        'routeIdxFrom': value.routeIdxFrom,
        'routeIdxTo': value.routeIdxTo,
    };
}

