/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagsType
 */
export interface TagsType {
    /**
     * 
     * @type {Array<string>}
     * @memberof TagsType
     */
    readonly tag: Array<string>;
}

/**
 * Check if a given object implements the TagsType interface.
 */
export function instanceOfTagsType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tag" in value;

    return isInstance;
}

export function TagsTypeFromJSON(json: any): TagsType {
    return TagsTypeFromJSONTyped(json, false);
}

export function TagsTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagsType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tag': json['tag'],
    };
}

export function TagsTypeToJSON(value?: TagsType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

