/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExternalContentType } from './ExternalContentType';
import {
    ExternalContentTypeFromJSON,
    ExternalContentTypeFromJSONTyped,
    ExternalContentTypeToJSON,
} from './ExternalContentType';
import type { FareSetItem } from './FareSetItem';
import {
    FareSetItemFromJSON,
    FareSetItemFromJSONTyped,
    FareSetItemToJSON,
} from './FareSetItem';
import type { KVType } from './KVType';
import {
    KVTypeFromJSON,
    KVTypeFromJSONTyped,
    KVTypeToJSON,
} from './KVType';

/**
 * 
 * @export
 * @interface TariffResult
 */
export interface TariffResult {
    /**
     * 
     * @type {Array<FareSetItem>}
     * @memberof TariffResult
     */
    readonly fareSetItem?: Array<FareSetItem>;
    /**
     * 
     * @type {string}
     * @memberof TariffResult
     */
    clickout?: string;
    /**
     * 
     * @type {ExternalContentType}
     * @memberof TariffResult
     */
    externalContent?: ExternalContentType;
    /**
     * 
     * @type {Array<KVType>}
     * @memberof TariffResult
     */
    readonly param?: Array<KVType>;
}

/**
 * Check if a given object implements the TariffResult interface.
 */
export function instanceOfTariffResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TariffResultFromJSON(json: any): TariffResult {
    return TariffResultFromJSONTyped(json, false);
}

export function TariffResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TariffResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fareSetItem': !exists(json, 'fareSetItem') ? undefined : ((json['fareSetItem'] as Array<any>).map(FareSetItemFromJSON)),
        'clickout': !exists(json, 'clickout') ? undefined : json['clickout'],
        'externalContent': !exists(json, 'externalContent') ? undefined : ExternalContentTypeFromJSON(json['externalContent']),
        'param': !exists(json, 'param') ? undefined : ((json['param'] as Array<any>).map(KVTypeFromJSON)),
    };
}

export function TariffResultToJSON(value?: TariffResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clickout': value.clickout,
        'externalContent': ExternalContentTypeToJSON(value.externalContent),
    };
}

