/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TechnicalMessage } from './TechnicalMessage';
import {
    TechnicalMessageFromJSON,
    TechnicalMessageFromJSONTyped,
    TechnicalMessageToJSON,
} from './TechnicalMessage';

/**
 * 
 * @export
 * @interface TechnicalMessages
 */
export interface TechnicalMessages {
    /**
     * 
     * @type {Array<TechnicalMessage>}
     * @memberof TechnicalMessages
     */
    technicalMessage?: Array<TechnicalMessage>;
}

/**
 * Check if a given object implements the TechnicalMessages interface.
 */
export function instanceOfTechnicalMessages(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TechnicalMessagesFromJSON(json: any): TechnicalMessages {
    return TechnicalMessagesFromJSONTyped(json, false);
}

export function TechnicalMessagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechnicalMessages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'technicalMessage': !exists(json, 'TechnicalMessage') ? undefined : ((json['TechnicalMessage'] as Array<any>).map(TechnicalMessageFromJSON)),
    };
}

export function TechnicalMessagesToJSON(value?: TechnicalMessages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TechnicalMessage': value.technicalMessage === undefined ? undefined : ((value.technicalMessage as Array<any>).map(TechnicalMessageToJSON)),
    };
}

