/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TechnicalMessage
 */
export interface TechnicalMessage {
    /**
     * 
     * @type {string}
     * @memberof TechnicalMessage
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof TechnicalMessage
     */
    key?: string;
}

/**
 * Check if a given object implements the TechnicalMessage interface.
 */
export function instanceOfTechnicalMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TechnicalMessageFromJSON(json: any): TechnicalMessage {
    return TechnicalMessageFromJSONTyped(json, false);
}

export function TechnicalMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TechnicalMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'key': !exists(json, 'key') ? undefined : json['key'],
    };
}

export function TechnicalMessageToJSON(value?: TechnicalMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'key': value.key,
    };
}

