/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TechnicalMessages } from './TechnicalMessages';
import {
    TechnicalMessagesFromJSON,
    TechnicalMessagesFromJSONTyped,
    TechnicalMessagesToJSON,
} from './TechnicalMessages';
import type { TimetableInfoType } from './TimetableInfoType';
import {
    TimetableInfoTypeFromJSON,
    TimetableInfoTypeFromJSONTyped,
    TimetableInfoTypeToJSON,
} from './TimetableInfoType';
import type { Warnings } from './Warnings';
import {
    WarningsFromJSON,
    WarningsFromJSONTyped,
    WarningsToJSON,
} from './Warnings';

/**
 * 
 * @export
 * @interface TimetableInfoList
 */
export interface TimetableInfoList {
    /**
     * 
     * @type {TechnicalMessages}
     * @memberof TimetableInfoList
     */
    technicalMessages?: TechnicalMessages;
    /**
     * 
     * @type {Warnings}
     * @memberof TimetableInfoList
     */
    warnings?: Warnings;
    /**
     * 
     * @type {string}
     * @memberof TimetableInfoList
     */
    serverVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof TimetableInfoList
     */
    dialectVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof TimetableInfoList
     */
    version?: string;
    /**
     * 
     * @type {Date}
     * @memberof TimetableInfoList
     */
    planRtTs?: Date;
    /**
     * 
     * @type {string}
     * @memberof TimetableInfoList
     */
    errorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof TimetableInfoList
     */
    errorText?: string;
    /**
     * 
     * @type {string}
     * @memberof TimetableInfoList
     */
    requestId?: string;
    /**
     * 
     * @type {Array<TimetableInfoType>}
     * @memberof TimetableInfoList
     */
    timetableInfo?: Array<TimetableInfoType>;
    /**
     * 
     * @type {string}
     * @memberof TimetableInfoList
     */
    begin?: string;
    /**
     * 
     * @type {string}
     * @memberof TimetableInfoList
     */
    end?: string;
}

/**
 * Check if a given object implements the TimetableInfoList interface.
 */
export function instanceOfTimetableInfoList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TimetableInfoListFromJSON(json: any): TimetableInfoList {
    return TimetableInfoListFromJSONTyped(json, false);
}

export function TimetableInfoListFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableInfoList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'technicalMessages': !exists(json, 'TechnicalMessages') ? undefined : TechnicalMessagesFromJSON(json['TechnicalMessages']),
        'warnings': !exists(json, 'Warnings') ? undefined : WarningsFromJSON(json['Warnings']),
        'serverVersion': !exists(json, 'serverVersion') ? undefined : json['serverVersion'],
        'dialectVersion': !exists(json, 'dialectVersion') ? undefined : json['dialectVersion'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'planRtTs': !exists(json, 'planRtTs') ? undefined : (new Date(json['planRtTs'])),
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
        'errorText': !exists(json, 'errorText') ? undefined : json['errorText'],
        'requestId': !exists(json, 'requestId') ? undefined : json['requestId'],
        'timetableInfo': !exists(json, 'TimetableInfo') ? undefined : ((json['TimetableInfo'] as Array<any>).map(TimetableInfoTypeFromJSON)),
        'begin': !exists(json, 'begin') ? undefined : json['begin'],
        'end': !exists(json, 'end') ? undefined : json['end'],
    };
}

export function TimetableInfoListToJSON(value?: TimetableInfoList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TechnicalMessages': TechnicalMessagesToJSON(value.technicalMessages),
        'Warnings': WarningsToJSON(value.warnings),
        'serverVersion': value.serverVersion,
        'dialectVersion': value.dialectVersion,
        'version': value.version,
        'planRtTs': value.planRtTs === undefined ? undefined : (value.planRtTs.toISOString()),
        'errorCode': value.errorCode,
        'errorText': value.errorText,
        'requestId': value.requestId,
        'TimetableInfo': value.timetableInfo === undefined ? undefined : ((value.timetableInfo as Array<any>).map(TimetableInfoTypeToJSON)),
        'begin': value.begin,
        'end': value.end,
    };
}

