/* tslint:disable */
/* eslint-disable */
/**
 * Proxy API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Warning } from './Warning';
import {
    WarningFromJSON,
    WarningFromJSONTyped,
    WarningToJSON,
} from './Warning';

/**
 * 
 * @export
 * @interface Warnings
 */
export interface Warnings {
    /**
     * 
     * @type {Array<Warning>}
     * @memberof Warnings
     */
    warning?: Array<Warning>;
}

/**
 * Check if a given object implements the Warnings interface.
 */
export function instanceOfWarnings(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WarningsFromJSON(json: any): Warnings {
    return WarningsFromJSONTyped(json, false);
}

export function WarningsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Warnings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'warning': !exists(json, 'Warning') ? undefined : ((json['Warning'] as Array<any>).map(WarningFromJSON)),
    };
}

export function WarningsToJSON(value?: Warnings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Warning': value.warning === undefined ? undefined : ((value.warning as Array<any>).map(WarningToJSON)),
    };
}

